services:
- type: web
  name: globstandpay 
  env: static
  buildCommand: npm run build  
  staticPublishPath: ./build
  routes:
    - type: rewrite
      source: /** 
      destination: /index.html

